## Tema 1. Funciones en Python

In [1]:
# Definamos una función de ejemplo

def funcion_ejemplo (parametro1, parametro2):
    variable_ejemplo = parametro1 + parametro2
    print(variable_ejemplo)

In [2]:
funcion_ejemplo(2,3)

5


In [3]:
def funcion_ejemplo1 (parametro1, parametro2):
    # variable_ejemplo = parametro1 + parametro2
    print(parametro1 + parametro2)

In [4]:
funcion_ejemplo1(4,3)

7


In [6]:
# Un ejemplo más práctico
# Se define la función

def suma(num_a,num_b):
    resultado = num_a + num_b
    print(f"El resultado de {num_a} + {num_b} es {resultado}")

In [17]:
# Habiendo definido la función, aquí empezamos el script:

a = 3
b = 7
c = 12

# Se invoca a la función, y se le agregan los parámetros

print(suma(a,b))
print(suma(c,b))

El resultado de 3 + 7 es 10
None
El resultado de 12 + 7 es 19
None


In [16]:
# 3 formas de combinar string con números
print("El resultado de", a,"+",b,"es",a+b)
print("El resultado de {} + {} es {}".format(a,b,a+b))
print(f"El resultado de {a} + {b} es {a+b}")

El resultado de 3 + 7 es 10
El resultado de 3 + 7 es 10
El resultado de 3 + 7 es 10


In [18]:
# ¿Qué pasaría si hacemos el ejercicio con string?
suma("hola"," mundo")

El resultado de hola +  mundo es hola mundo


## Tema 2. Devolver resultado de una función

In [19]:
# Return
# Se define la función

def suma_1(num_1,num_2):
    resultado = num_1 + num_2
    return resultado

In [22]:
a = 5
b = 10

# Se invoca la función:
res = suma_1(a,b) # Se almacena el resultado de la función en la variable "res"

print(f"El resultado de {a} + {b} es {res}")

El resultado de 5 + 10 es 15


## Tema 3. Funciones Integradas

In [25]:
# Longitud de una cadena
print(len("Hola Mundo"))

10


In [26]:
# Conversión en mayúsculas y minúsculas
nombre = "Carlos"
print(nombre)
print(nombre.upper())
print(nombre.lower())

Carlos
CARLOS
carlos


In [29]:
# Reemplazar una cadena por otra
texto = "Hoy es viernes"
print(texto.replace("Hoy es viernes","mi cuerpo lo sabe"))

mi cuerpo lo sabe


In [30]:
# Determinar el máximo y mínimo
lista_nros = [2, 5, 10]
print(max(lista_nros))
print(min(lista_nros))
print(max(lista_nros) - min(lista_nros))

10
2
8


In [31]:
# Suma de lista de números
lista_nros = [2, 5, 10]
print(sum(lista_nros))

17


In [36]:
# Crear rango de números
A = range(10)
print(A)
print(type(A))

range(0, 10)
<class 'range'>


In [37]:
print(list(A))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## Tema 4. Instalación y uso de librerías externas

### Trabajemos con NumPy

In [38]:
# Si no tienen instalada la librería, se puede instalar con pip install
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [39]:
pip --version

pip 21.0.1 from C:\Users\gonza\anaconda3\lib\site-packages\pip (python 3.8)

Note: you may need to restart the kernel to use updated packages.


In [43]:
# Importando NumPy
import numpy as np # Se puede generar el alias (numpy abreviado)

x = [2, 3, 4, 5] # Se crea una lista
nums = np.array(x) # Vamos a crear un arreglo (objeto principal de NumPy), desde una lista
print(x)
print(nums)
print(type(x))
print(type(nums))

[2, 3, 4, 5]
[2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [45]:
x = [1, 2, 3]
y = [2, 3, 4]

np.array(x,y)
np.array([x,y])

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
# Vector (arreglo) de más de una dimensión (matriz)
import numpy as np

nums = np.array([[1,2,3],[4,5,6]])
print(nums)

[[1 2 3]
 [4 5 6]]


### Trabajemos con Requests

In [53]:
# pip install requests # REVISAR
import requests

response = requests.get("https://github.com")
print(response.status_code)

200


In [59]:
import requests
import json

url = "https://sv443.net/jokeapi/v2/joke/Pun?type=twopart"

joke = requests.get(url=url).json()

print(json.dumps(joke,indent=2))

{
  "error": false,
  "category": "Pun",
  "type": "twopart",
  "setup": "Did you hear about the cheese factory that exploded in France?",
  "delivery": "There was nothing but de brie.",
  "flags": {
    "nsfw": false,
    "religious": false,
    "political": false,
    "racist": false,
    "sexist": false,
    "explicit": false
  },
  "id": 65,
  "safe": true,
  "lang": "en"
}
